# RabbitMQ stuff
services:
    wallabag_import.consumer.ampq.pocket:
        class: Wallabag\ImportBundle\Consumer\AMPQEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_user.user_repository"
            - "@wallabag_import.pocket.import"
            - "@logger"
    wallabag_import.consumer.ampq.readability:
        class: Wallabag\ImportBundle\Consumer\AMPQEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_user.user_repository"
            - "@wallabag_import.readability.import"
            - "@logger"
    wallabag_import.consumer.ampq.wallabag_v1:
        class: Wallabag\ImportBundle\Consumer\AMPQEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_user.user_repository"
            - "@wallabag_import.wallabag_v1.import"
            - "@logger"
    wallabag_import.consumer.ampq.wallabag_v2:
        class: Wallabag\ImportBundle\Consumer\AMPQEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_user.user_repository"
            - "@wallabag_import.wallabag_v2.import"
            - "@logger"
