parameters:
    addons_url:
        firefox: https://addons.mozilla.org/firefox/addon/wallabag-v2/
        chrome: https://chrome.google.com/webstore/detail/wallabagit/peehlcgckcnclnjlndmoddifcicdnabm
        f_droid: https://f-droid.org/app/fr.gaulupeau.apps.InThePoche
        google_play: https://play.google.com/store/apps/details?id=fr.gaulupeau.apps.InThePoche
        ios: https://itunes.apple.com/app/wallabag/id828331015?mt=8
        windows: https://www.microsoft.com/store/apps/wallabag/9nblggh11646
